### ISSUE TITLE
Ast2600 A1 not booted after enable secure boot 

### ISSUE THREAD

**Issue by hitesh0803** [AspeedTech-BMC/socsec#16]
setups i am followed to complied secure boot 

1) generate rsa public private key using opnssl .
 -> openssl genrsa -out rsa_oem_dss_key.pem 1024 
-> openssl rsa -in rsa_oem_dss_key.pem -pubout -out rsa_pub_oem_dss_key.pem
2) add public key name into this  (2600-a1_mode2-rsa1024-sha224.json).
3) configure and compile.
4) programed  otp memory using u-boot utility.
5) Burn secure boot image and boot.

problem:- during booting only two word( S2 ) print on uart console.

**Comment by Neal-liu** [comment]
Please try AST2600 A3 chip.
We are not going to support A1 anymore.
Thanks.
