### ISSUE TITLE
hexdump dependency is abandoned

### ISSUE THREAD

**Issue by amboar** [AspeedTech-BMC/socsec#5]
Here's the `hexdump` package listing on pypi:

https://pypi.org/project/hexdump/

The `Homepage` link (https://bitbucket.org/techtonik/hexdump/) points bitbucket, but repository has been removed (the link 404's). Some searching suggests the package was not migrated to e.g. Github, and it hasn't seen a release since 2016.

It's probably worth reconsidering this dependency.

**Comment by johnydhuang** [comment]
I will remove this dependency and implement a hex print function into socsec.

**Comment by amboar** [comment]
I thought about that and didn't feel comfortable reimplementing it myself in case I broke something and bricked a SoC. Might be good to add coverage for the hex bits to the test suite.

**Comment by johnydhuang** [comment]
`hexdump` just used to print some bytearray information, it will not affect the output image.
#10 remove the `hexdump` dependency, I think it is safe.
